baseURL = "https://blog.jinosoft.com/"
defaultContentLanguage = "ko"
locale = "ko-KR"
title = "지노소프트 기술 블로그"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 0

[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 100

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
