disabled = false
locale = "ko-KR"
label = "한국어"
weight = 1
title = "Jino Blog"

[params]
  displayName = "KO"
  isoCode = "ko"
  rtl = false
  dateFormat = "2006년 1월 2일"

  [params.author]
    name = "Jino"
